import { Inter } from "next/font/google";
import "./globals.css";
import Left_sideBar from "../components/Left_sideBar";
import Top_bar from "../components/Top_bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={(inter.className, "bg-lightPurple overflow-x-hidden")}>
        <div className="flex lg:flex-row sm:flex-col lg:gap-0 sm:gap-4">
          <Left_sideBar />
          <div className="flex flex-col lg:gap-0 sm:gap-24">
            <Top_bar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
